steps:
  # Install Firebase CLI
  - name: 'node:latest'
    entrypoint: 'npm'
    args: ['install', '-g', 'firebase-tools']

  # Deploy static site to Firebase Hosting
  # Uses Cloud Build's default service account for authentication
  - name: 'node:latest'
    entrypoint: 'firebase'
    args:
      - 'deploy'
      - '--project=$PROJECT_ID'
      - '--only=hosting'
      - '--non-interactive'

# Optional: Faster builds, cleaner logs
options:
  logging: CLOUD_LOGGING_ONLY

# Optional: Get notified on Slack/email when builds complete
# (can configure later in Cloud Build settings)